# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Homepage
name: El houcine Bergou
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#repository_url: http://www.google.com
# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"

minimal_mistakes_skin: "aqua"  # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

# Site Author
author:
  name             : "El houcine Bergou"
  avatar           : "as.jpg" # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "Assistant Professor at UM6P"
  location         : "UM6P-CS, Ben Guerir"
  email            : "elhoucine.bergou@um6p.ma"
  uri              :
  bitbucket        :
  foursquare       :
  github           : "https://github.com/ehbergou/"
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
#  linkedin         : "https://www.linkedin.com/in/ehbergou/"
  pinterest        :
  soundcloud       :
  stackoverflow    : 
  steam            :
  tumblr           :
  vine             :
  weibo            :
  xing             :
  youtube          :			

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      share: true
      overlay_image: unsplash-gallery-image-2.jpg
      related: false
#  uri    : "http://your-site.com"
#  home   : # null (default), "absolute or relative url to link to author home"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
